-- SpendSense PostgreSQL schema (idempotent: safe for empty DBs and legacy Hibernate-created tables)

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255),
    google_sub      VARCHAR(255),
    auth_provider   VARCHAR(32)  NOT NULL DEFAULT 'LOCAL',
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    role            VARCHAR(32),
    openai_api_key_encrypted TEXT
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS google_sub VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(32);
ALTER TABLE users ADD COLUMN IF NOT EXISTS openai_api_key_encrypted TEXT;

UPDATE users SET auth_provider = 'LOCAL' WHERE auth_provider IS NULL;
ALTER TABLE users ALTER COLUMN auth_provider SET DEFAULT 'LOCAL';
ALTER TABLE users ALTER COLUMN auth_provider SET NOT NULL;

ALTER TABLE users ALTER COLUMN password DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS users_google_sub_key ON users (google_sub);

CREATE TABLE IF NOT EXISTS transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description      VARCHAR(255) NOT NULL,
    amount           NUMERIC(19, 2) NOT NULL,
    type             VARCHAR(32) NOT NULL,
    category         VARCHAR(32) NOT NULL,
    transaction_date TIMESTAMP NOT NULL,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    user_id          BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS budgets (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    amount            NUMERIC(19, 2) NOT NULL,
    category          VARCHAR(32) NOT NULL,
    period            VARCHAR(32) NOT NULL,
    start_date        TIMESTAMP NOT NULL,
    end_date          TIMESTAMP NOT NULL,
    spent_amount      NUMERIC(19, 2) DEFAULT 0,
    remaining_amount  NUMERIC(19, 2),
    is_active         BOOLEAN DEFAULT TRUE,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    user_id           BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS bills (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payee_name             VARCHAR(255) NOT NULL,
    amount                 NUMERIC(19, 2) NOT NULL,
    due_date               DATE NOT NULL,
    paid                   BOOLEAN NOT NULL DEFAULT FALSE,
    paid_at                TIMESTAMP,
    linked_transaction_id  BIGINT,
    created_at             TIMESTAMP,
    updated_at             TIMESTAMP,
    user_id                BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type           VARCHAR(32) NOT NULL,
    title          VARCHAR(255) NOT NULL,
    message        VARCHAR(500) NOT NULL,
    "read"         BOOLEAN NOT NULL DEFAULT FALSE,
    reference_type VARCHAR(64),
    reference_id   BIGINT,
    created_at     TIMESTAMP,
    user_id        BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS receipt_attachments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename   VARCHAR(255) NOT NULL,
    content_type      VARCHAR(128) NOT NULL,
    size_bytes        BIGINT NOT NULL,
    created_at        TIMESTAMP,
    transaction_id    BIGINT NOT NULL,
    user_id           BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS receipt_attachments_transaction_id_key ON receipt_attachments (transaction_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transactions_user') THEN
        ALTER TABLE transactions
            ADD CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_budgets_user') THEN
        ALTER TABLE budgets
            ADD CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bills_user') THEN
        ALTER TABLE bills
            ADD CONSTRAINT fk_bills_user FOREIGN KEY (user_id) REFERENCES users (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bills_linked_transaction') THEN
        ALTER TABLE bills
            ADD CONSTRAINT fk_bills_linked_transaction FOREIGN KEY (linked_transaction_id) REFERENCES transactions (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notifications_user') THEN
        ALTER TABLE notifications
            ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_receipt_attachments_transaction') THEN
        ALTER TABLE receipt_attachments
            ADD CONSTRAINT fk_receipt_attachments_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_receipt_attachments_user') THEN
        ALTER TABLE receipt_attachments
            ADD CONSTRAINT fk_receipt_attachments_user FOREIGN KEY (user_id) REFERENCES users (id);
    END IF;
END $$;
