-- Category rules, user notification prefs, recurring bills

CREATE TABLE IF NOT EXISTS category_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    pattern     VARCHAR(100) NOT NULL,
    category    VARCHAR(32) NOT NULL,
    priority    INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_category_rules_user ON category_rules (user_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_category_rules_user') THEN
        ALTER TABLE category_rules
            ADD CONSTRAINT fk_category_rules_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
    END IF;
END $$;

ALTER TABLE users ADD COLUMN IF NOT EXISTS bill_reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bill_reminder_days_before INT NOT NULL DEFAULT 3;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_bill_reminder_sent_at TIMESTAMP;

ALTER TABLE bills ADD COLUMN IF NOT EXISTS recurring BOOLEAN NOT NULL DEFAULT FALSE;
